/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.util.LinkedList;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mhasa
 */
public class AdminWordScreen extends javax.swing.JFrame {
	DefaultTableModel tblModel;
	LinkedList<String> kelimeList = new LinkedList<>();
	LinkedList<String> anlamList = new LinkedList<>();
	WordQuiz wordQuiz= new WordQuiz();
	// DefaultTableModel model;

	public AdminWordScreen() {
		initComponents();
		tblModel = (DefaultTableModel) jTable2.getModel();

		String veri1[] = { "Banana", "Muz" };
		String veri2[] = { "Computer", "Bilgisayar" };
		String veri3[] = { "Door", "Kapı" };
		String veri4[] = { "pencil", "kalem" };
		String veri5[] = { "hand", "el" };

		tblModel.addRow(veri1);
		tblModel.addRow(veri2);
		tblModel.addRow(veri3);
		tblModel.addRow(veri4);
		tblModel.addRow(veri5);

		tblModel.removeRow(0);

		kelimeList.add("Banana");
		kelimeList.add("Computer");
		kelimeList.add("Door");
		kelimeList.add("pencil");
		kelimeList.add("hand");
		
		anlamList.add("Muz");
		anlamList.add("Bilgisayar");
		anlamList.add("Kapı");
		anlamList.add("kalem");
		anlamList.add("el");
		
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable2 = new javax.swing.JTable();
		jLabel2 = new javax.swing.JLabel();
		addKelime = new javax.swing.JButton();
		updateKelime = new javax.swing.JButton();
		printfKelime = new javax.swing.JButton();
		jdeleteKelime = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		jToggleButton1 = new javax.swing.JToggleButton();
		kelimeAlani = new javax.swing.JTextField();
		anlamAlani = new javax.swing.JTextField();
		geributton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(0, 0, 255));
		jLabel1.setText("Kelime Yönetimi");

		jTable2.setModel(new javax.swing.table.DefaultTableModel(new Object[][] { { null, null } },
				new String[] { "Cevap", "Anlamı" }) {
			Class[] types = new Class[] { java.lang.String.class, java.lang.String.class };

			public Class getColumnClass(int columnIndex) {
				return types[columnIndex];
			}
		});
		jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jTable2MouseClicked(evt);
			}
		});
		jScrollPane1.setViewportView(jTable2);

		jLabel2.setText("Kelime:");

		addKelime.setText("Ekle");
		addKelime.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				addKelimeActionPerformed(evt);
			}
		});

		updateKelime.setText("Güncelle");
		updateKelime.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				updateKelimeActionPerformed(evt);
			}
		});

		printfKelime.setText("Yazdır");
		printfKelime.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				printfKelimeActionPerformed(evt);
			}
		});

		jdeleteKelime.setForeground(new java.awt.Color(153, 153, 153));
		jdeleteKelime.setText("Silinecek sorunun satırını girin");
		jdeleteKelime.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jdeleteKelimeMouseClicked(evt);
			}
		});
		jdeleteKelime.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jdeleteKelimeActionPerformed(evt);
			}
		});

		jLabel6.setText("Anlamı:");

		jToggleButton1.setText("Sil\n");
		jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jToggleButton1ActionPerformed(evt);
			}
		});

		kelimeAlani.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				kelimeAlaniActionPerformed(evt);
			}
		});

		geributton.setBackground(new java.awt.Color(255, 0, 51));
		geributton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		geributton.setForeground(new java.awt.Color(255, 255, 255));
		geributton.setText("Geri ");
		geributton.setActionCommand("Geri\n");
		geributton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				JFrame adminChoseFrame = new AdminChoseScreen();
				dispose();

				adminChoseFrame.setMinimumSize(getMinimumSize());
				adminChoseFrame.pack();
				adminChoseFrame.setVisible(true);
				geributtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
						.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
								.createSequentialGroup().addContainerGap()
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(layout.createSequentialGroup()
												.addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 59,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(anlamAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 71,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(layout.createSequentialGroup()
												.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(kelimeAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 71,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(layout.createSequentialGroup()
												.addComponent(addKelime, javax.swing.GroupLayout.PREFERRED_SIZE, 72,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(18, 18, 18).addComponent(updateKelime).addGap(18, 18, 18)
												.addComponent(printfKelime))))
								.addGroup(layout.createSequentialGroup().addGap(41, 41, 41)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jdeleteKelime, javax.swing.GroupLayout.PREFERRED_SIZE,
														195, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE,
														72, javax.swing.GroupLayout.PREFERRED_SIZE))))
						.addGap(0, 498, Short.MAX_VALUE)).addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
								layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE).addComponent(geributton)))
				.addContainerGap())
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
						.createSequentialGroup().addContainerGap(316, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										layout.createSequentialGroup()
												.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 224,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(220, 220, 220))
								.addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING,
										javax.swing.GroupLayout.PREFERRED_SIZE, 375,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap())));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(geributton).addGap(34, 34, 34)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(kelimeAlani, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(29, 29, 29)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(anlamAlani, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(28, 28, 28)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(addKelime).addComponent(updateKelime).addComponent(printfKelime))
						.addGap(53, 53, 53)
						.addComponent(jdeleteKelime, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(jToggleButton1).addContainerGap(57, Short.MAX_VALUE))
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addContainerGap()
								.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
								.addContainerGap())));

		pack();
	}// </editor-fold>

	private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {
		DefaultTableModel tblModel = (DefaultTableModel) jTable2.getModel();

		String tblKelime = tblModel.getValueAt(jTable2.getSelectedRow(), 0).toString();
		String tblAnlam = tblModel.getValueAt(jTable2.getSelectedRow(), 1).toString();

		kelimeAlani.setText(tblKelime);
		anlamAlani.setText(tblAnlam);
	}


	private void addKelimeActionPerformed(java.awt.event.ActionEvent evt) {
		String word = kelimeAlani.getText();
		String mean = anlamAlani.getText();
		wordQuiz.add(word, mean, tblModel, kelimeList, anlamList);
		// model.insertRow(model.getRowCount(),new
		// Object[]{kelime.getText(),SecenekA.getText(),SecenekB.getText(),SecenekC.getText()});
	}

	private void updateKelimeActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		DefaultTableModel tblmodel = (DefaultTableModel) jTable2.getModel();
		String sozcuk = kelimeAlani.getText();
		String anlami = anlamAlani.getText();
		int satir = jTable2.getSelectedRow();
		int satirCount = jTable2.getSelectedRowCount();
		wordQuiz.update(sozcuk, anlami, tblmodel, satir, satirCount, kelimeList, anlamList);
	}

	private void jdeleteKelimeActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		jdeleteKelime.setText("");
	}

	private void jdeleteKelimeMouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		jdeleteKelime.setText("");
	}

	private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		DefaultTableModel tblmodel = (DefaultTableModel) jTable2.getModel();
		String satir = jdeleteKelime.getText();

		if (satir != "") {

			try {
				wordQuiz.delete(satir,tblmodel,kelimeList,anlamList,jdeleteKelime);
				jdeleteKelime.setText(""); 
			} catch (Exception e) {
				JOptionPane.showMessageDialog(this, "Geçerli Değer Giriniz", "uyari", JOptionPane.WARNING_MESSAGE);
			}
		} else
			JOptionPane.showMessageDialog(this, "Değer girilmedi!!!");
	}

	private void kelimeAlaniActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void printfKelimeActionPerformed(java.awt.event.ActionEvent evt) {
		wordQuiz.printList(kelimeList,anlamList);
	}

	private void geributtonActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(AdminWordScreen.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(AdminWordScreen.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(AdminWordScreen.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(AdminWordScreen.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new AdminWordScreen().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton addKelime;
	private javax.swing.JTextField anlamAlani;
	private javax.swing.JButton geributton;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable2;
	private javax.swing.JToggleButton jToggleButton1;
	private javax.swing.JTextField jdeleteKelime;
	private javax.swing.JTextField kelimeAlani;
	private javax.swing.JButton printfKelime;
	private javax.swing.JButton updateKelime;

	// End of variables declaration
}